import type { CountKey, HistoryDraw } from '../types/lotto';
import { buildStats } from './lottoStats';

export type Recommendation = { numbers: number[]; score: number; reasons: string[] };
function shuffle<T>(array: T[]): T[] { const result = [...array]; for (let i = result.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [result[i], result[j]] = [result[j], result[i]]; } return result; }
function clamp(value: number, min: number, max: number) { return Math.min(max, Math.max(min, value)); }
function consecutiveCount(numbers: number[]) { const sorted = [...numbers].sort((a, b) => a - b); let count = 0; for (let i = 1; i < sorted.length; i++) if (sorted[i] === sorted[i - 1] + 1) count++; return count; }
function scoreCombination(numbers: number[], draws: HistoryDraw[]) { const stats = buildStats(draws); const reasons: string[] = []; const analysis = stats.numberAnalysis; const frequencies = numbers.map(n => analysis[n - 1]?.frequency ?? 0); const avgFrequency = frequencies.reduce((a, b) => a + b, 0) / 6; const expected = draws.length * 6 / 45; const frequencyScore = clamp(10 - Math.abs(avgFrequency - expected) * 1.5, 0, 10); const recent = numbers.map(n => analysis[n - 1]?.recentFrequency ?? 0); const recentAvg = recent.reduce((a, b) => a + b, 0) / 6; const recentScore = clamp(8 - Math.abs(recentAvg - 2), 0, 8); const odd = numbers.filter(n => n % 2 === 1).length; const commonPattern = stats.oddEvenPatterns[0]; const oddEvenScore = commonPattern ? clamp(10 - Math.abs(odd - commonPattern.odd) * 3, 0, 10) : 5; const occupiedRanges = stats.rangeDistribution.filter((r: { min: number; max: number }) => numbers.some(n => n >= r.min && n <= r.max)).length; const rangeScore = occupiedRanges >= 4 ? 10 : occupiedRanges === 3 ? 7 : occupiedRanges === 2 ? 4 : 1; const sum = numbers.reduce((a, b) => a + b, 0); const sumScore = clamp(10 - Math.abs(sum - stats.averageSum) / 12, 0, 10); const consecutive = consecutiveCount(numbers); const consecutiveScore = consecutive <= 2 ? 8 : consecutive === 3 ? 4 : 1; const total = frequencyScore + recentScore + oddEvenScore + rangeScore + sumScore + consecutiveScore; if (frequencyScore >= 7) reasons.push('출현 빈도 균형'); if (recentScore >= 5) reasons.push('최근 출현 흐름 반영'); if (oddEvenScore >= 7) reasons.push(`홀짝 ${odd}:${6 - odd}`); if (rangeScore >= 7) reasons.push('번호 구간 분산'); if (sumScore >= 7) reasons.push('평균 합계 근접'); if (consecutive <= 2) reasons.push(consecutive === 0 ? '연속번호 없음' : `연속번호 ${consecutive}쌍`); return { score: Math.round(total / 56 * 100), reasons }; }
export function makeCombination(requiredNumbers: number[] = [], excludedNumbers: number[] = []) { const required = [...new Set(requiredNumbers)].filter(n => n >= 1 && n <= 45); const excluded = new Set(excludedNumbers); const available = Array.from({ length: 45 }, (_, i) => i + 1).filter(n => !excluded.has(n) || required.includes(n)); const selected = required.slice(0, 6); const remaining = available.filter(n => !selected.includes(n)); return [...selected, ...shuffle(remaining).slice(0, 6 - selected.length)].sort((a, b) => a - b); }
export function generateRecommendations(count: CountKey, requiredNumbers: number[] = [], excludedNumbers: number[] = [], draws: HistoryDraw[] = []): Recommendation[] { const results: Recommendation[] = []; const attempts = count * 300; let tries = 0; while (results.length < Math.max(count * 10, count) && tries < Math.max(500, attempts)) { tries++; const numbers = makeCombination(requiredNumbers, excludedNumbers); if (results.some(r => r.numbers.join(',') === numbers.join(','))) continue; const scored = draws.length ? scoreCombination(numbers, draws) : { score: 0, reasons: ['통계 데이터 없음'] }; results.push({ numbers, ...scored }); } results.sort((a, b) => b.score - a.score); const pool = shuffle(results.slice(0, Math.max(count * 3, 10))); return pool.slice(0, count).sort((a, b) => b.score - a.score); }
